const endPoints = {
  transactionsSchemas: "transactions/schemas",
  networkStatus: "network/status",
  accounts: "accounts",
  address: "?address=",
  blocks: "blocks",
  fees: "fees",
  network: "network/",
  statistics: "statistics",
  status: "status",
  peers: "peers",
  connected: "/connected",
  disconnected: "/disconnected",
  spec: "spec",
  transactions: "transactions",
  transactionsByAddress: "?address=",
  transactionsID: "?transactionId=",
  senderPublicKey: "?senderPublicKey=",
  nonce: "&nonce=",
  schemas: "/schemas",
  moduleAssetID: "?moduleAssetId=",
  moduleAssetName: "?moduleAssetName=",
  day: "/day",
  month: "/month",
  votesReceived: "votes_received?publickey=",
  username: "&username=",
  peersState: "?state=",
  peersIP: "?ip=",
};

export default endPoints;
