import grid from "flexboxgrid/dist/flexboxgrid.css";

export default [
  {
    title: "Block ID",
    classList: `${grid["col-xs"]}`,
  },
  {
    title: "Height",
    classList: `${grid["col-xs"]}`,
  },
  {
    title: "Date",
    classList: `${grid["col-xs"]}`,
  },
  {
    title: "Transactions",
    classList: `${grid["col-xs"]}`,
  },
  {
    title: "Generated by",
    classList: `${grid["col-xs-3"]}`,
  },
  {
    title: "Block Reward",
    classList: `${grid["col-xs-2"]}`,
  },
];
